[project]
name = "keystone_role_assignment_openfga"
authors = [
  {name = "Artem Goncharov"},
]
description = "OpenStack Keystone role assignment plugin using OpenFGA"
readme = {file="README.rst", content-type="text/x-rst"}
dynamic = ["version"]
requires-python = ">=3.9,<3.13"
license = { text = "Apache-2.0" }
dependencies = [
  "keystone>=24.0",
  "oslo.cache",
  "oslo.config",
  "oslo.log",
  "requests"
]
classifiers = [
  "Environment :: OpenStack",
  "Intended Audience :: Information Technology",
  "Intended Audience :: System Administrators",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]

[build-system]
requires = ["pbr>=6.0.0", "setuptools>=64.0.0"]
build-backend = "pbr.build"

[dependency-groups]
dev = [
  "pytest >=8.1.1,<9",
  "pytest-mock >=3.15,<4",
  "requests-mock",
  "openstacksdk >=4.0,<5"
]

[project.entry-points."keystone.assignment"]
openfga = "keystone_role_assignment_openfga.plugin:OpenFGA"
openfga_sql_multiplex = "keystone_role_assignment_openfga.multiplex_plugin:OpenFGASqlMultiplex"

[tool.setuptools]
packages = [
  "keystone_role_assignment_openfga"
]

[tool.ruff]
line-length = 79
target-version = "py39"

[tool.ruff.lint]
# enable the following rule classes:
#
# C4: https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4
# UP: https://docs.astral.sh/ruff/rules/#pyupgrade-up
select = ["C4", "UP"]

[tool.ruff.format]
quote-style = "double"
docstring-code-format = true
docstring-code-line-length = 40
skip-magic-trailing-comma = true
preview = true

[tool.uv]

[tool.pytest]
log_level = "debug"
log_cli = true
log_cli_level = "debug"

[tool.pyright]
venvPath = "."
venv = ".venv"
reportMissingImports = "warning"
