name: Integration

on:
  workflow_dispatch:
  pull_request:

env:
  OS_KEYSTONE_CONFIG_DIR: ${{ github.workspace }}/etc

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        backend: ["openfga", "openfga_sql_multiplex"]
    name: Integration-${{ matrix.backend }}
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: openfga
          POSTGRES_PASSWORD: '1234'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      postgres-keystone:
        image: postgres:17
        env:
          POSTGRES_USER: keystone
          POSTGRES_PASSWORD: '1234'
        ports:
          - 5433:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      OPENFGA_DATASTORE_ENGINE: 'postgres'
      OPENFGA_DATASTORE_URI: 'postgres://openfga:1234@127.0.0.1:5432/openfga'
      OPENFGA_LOG_LEVEL: debug
      OPENFGA_AUTHN_METHOD: "preshared"
      OPENFGA_AUTHN_PRESHARED_KEYS: "foobarkey"
      FGA_API_TOKEN: "foobarkey"
      OPENFGA_PLAYGROUND_ENABLED: "false"

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Install OpenFGA server
        uses: jaxxstorm/action-install-gh-release@v2.1.0
        with:
          repo: openfga/openfga
          tag: v1.10.3
          cache: enable

      - name: Migrate OpenFGA database
        shell: bash
        run: openfga migrate

      - name: Start OpenFGA server in background
        shell: bash
        run: openfga run > fga.log 2>&1 &

      - name: Install OpenFGA cli
        uses: jaxxstorm/action-install-gh-release@v2.1.0
        with:
          repo: openfga/cli
          cache: enable

      - name: Install jq
        uses: dcarbone/install-jq-action@v3

      - name: Create store with model
        id: 'store'
        run: |
          fga store create --model ./etc/fga.model > store_response.json
          cat store_response.json
          store_id=$(jq -r '.store.id' store_response.json)
          model_id=$(jq -r '.model.authorization_model_id' store_response.json)
          echo "store_id=${store_id}" >> $GITHUB_OUTPUT
          echo "model_id=${model_id}" >> $GITHUB_OUTPUT

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install necessary python packages
        run: pip install keystone uwsgi psycopg2 .

      - name: Prepare keystone config file
        env:
          store_id: ${{ steps.store.outputs.store_id }}
          model_id: ${{ steps.store.outputs.model_id }}
        run: |
          cat <<EOF > etc/keystone.conf
          [DEFAULT]
          debug = true
          [fga]
          api_url = http://localhost:8080
          store_id = ${store_id}
          model_id = ${model_id}
          api_key = foobarkey
          domains_using_sql_backend = default
          role_to_relation_name = reader:can_be_reader,member:can_be_member,manager:can_be_manager,admin:can_be_admin,service:can_be_service

          [assignment]
          driver = ${{ matrix.backend }}

          [database]
          connection = postgresql://keystone:1234@127.0.0.1:5433/keystone

          [fernet_receipts]
          key_repository = $(pwd)/etc/fernet

          [fernet_tokens]
          key_repository = $(pwd)/etc/fernet
          EOF
          cat etc/keystone.conf

      - name: Prepare clouds.yaml
        run: |
          mkdir -p ~/.config/openstack
          cat <<EOF > ~/.config/openstack/clouds.yaml
          clouds:
            admin:
              auth:
                auth_url: http://localhost:5001
                username: admin
                password: password
                project_name: admin
                user_domain_id: default
                project_domain_id: default
              interface: public
          EOF

      - name: Init keystone
        run: |
          mkdir -p etc/fernet
          keystone-manage --config-file etc/keystone.conf db_sync
          keystone-manage --config-file etc/keystone.conf fernet_setup
          keystone-manage --config-file etc/keystone.conf bootstrap --bootstrap-password password --bootstrap-public-url http://localhost:5001

      - name: Start python keystone
        run: uwsgi --module "keystone.server.wsgi:initialize_public_application()" --http-socket :5001 -b 65535 --http-keepalive --so-keepalive --logformat "Request %(uri):%(method) returned %(status) in %(msecs)ms" > python.log 2>&1 &

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Run the tests
        run: uv run pytest keystone_role_assignment_openfga/tests/functional

      - name: Dump python keystone log
        if: always()
        run: cat python.log

      - name: Dump fga log
        if: always()
        run: cat fga.log
